app:
  scheduler:
    enable: false
    interval: 300000 #5 min
    force-check-delay: 10000
    scan-links-limit: 100
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false



server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github:
    base-url: https://api.github.com
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500
      codes: 400
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3/
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500
      codes: 400,401
  bot:
    base-url: http://localhost:8090
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500
      codes:

springdoc:
  swagger-ui:
    path: /swagger-ui

