app:
  scheduler:
    enable: true
    interval: 300000 #5 min
    force-check-delay: 10000
    scan-links-limit: 100
  database-access-type: jdbc
  use-queue: true

kafka:
  bootstrap-servers: localhost:29091
  topic: scrapper.link-updates

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  kafka:
    admin:
      auto-create: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github:
    base-url: https://api.github.com
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3/
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500
  bot:
    base-url: http://localhost:8090
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500

springdoc:
  swagger-ui:
    path: /swagger-ui

rate-limiter:
  enable: true
  capacity: 5000
  refill:
    tokens: 5000
    period: PT1H
