app:
  scheduler:
    enable: true
    interval: 300000 #5 min
    force-check-delay: 10000
    scan-links-limit: 100
  database-access-type: jpa

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/scrapper"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false



server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github:
    baseUrl: https://api.github.com
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3/
  bot:
    baseUrl: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui

