app:
  telegram-token: ${TELEGRAM_API_TOKEN}
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    admin:
      auto-create: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

client:
  scrapper:
    base-url: http://localhost:8080
    retry:
      enable: true
      type: constant
      max-attempts: 3
      delay: 500

rate-limiter:
  enable: true
  capacity: 5000
  refill:
    tokens: 5000
    period: PT1H

kafka:
  enable: true
  bootstrap-servers: localhost:29091
  scrapper-topic: scrapper.link-updates
  consumer-group: message-group
  dlq-topic: bot.scrapper-link-updates_dlq

management:
  server:
    port: 8091
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: "/metrics"
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
